goproto:
	@protoc --go_out=service/grpc/pb --go_opt=paths=source_relative --go-grpc_out=service/grpc/pb --go-grpc_opt=paths=source_relative --proto_path=service/grpc/protofiles service/grpc/protofiles/*.proto
