version: "3"

# topics:
# kafka-topics --list --bootstrap-server=kafka:9092
# kafka-topics --create --topic=mytest --if-not-exists --bootstrap-server=kafka:9092
# groups:
# kafka-consumer-groups --list --bootstrap-server=kafka:9092
# kafka-consumer-groups --describe --all-groups --bootstrap-server=kafka:9092
# consumer:
# kafka-console-consumer --topic=mytest --bootstrap-server=kafka:9092
# producer:
# kafka-console-producer --topic=mytest --bootstrap-server=kafka:9092
# {"routeId":"1","clientId":"1"}
# {"routeId":"1","clientId":"1","position":[-15.82651,-47.92878],"finished":false}
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    command: >
      bash -c 
        "sleep 5s &&
        kafka-topics --create --topic=transactions --if-not-exists --bootstrap-server=kafka:9092 &&
        kafka-topics --create --topic=transaction-confirmation --if-not-exists --bootstrap-server=kafka:9092 &&
        kafka-topics --create --topic=bank001 --if-not-exists --bootstrap-server=kafka:9092 &&
        kafka-topics --create --topic=bank002 --if-not-exists --bootstrap-server=kafka:9092"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - kafka

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021  
