version: '3'

services:
  db-test:
    image: postgres:13-alpine
    container_name: db-test
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    extra_hosts:
      - 'host.docker.internal:host-gateway'
